name: Nanopi R2S Openwrt Build

on:
  workflow_dispatch:
#   push:
#     paths-ignore:
#       - '.github/**'
#     branches:
#       - r2s
  #schedule:
  #  - cron: '0 19 * * 6'
  watch:
    types: started

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    container:
      image: lingjiehao/build-envs:r2s
      volumes: 
        - /r2s:/r2s

    steps:
      
      - name: Sync and Build
        run: |
            cd /r2s
            repo init -u https://github.com/lingjiehao/manifests -b r2s
            repo sync --no-tags -cd -j8 2>&1 | tee -a build.log
            ./build.sh 2>&1 | tee -a build.log
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Openwrt
          path: |
            /r2s/bin/targets/rockchip/armv8/*-sysupgrade.img.gz
  
      - name: Upload Fail Log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: log
          path: /r2s/build.log
        
          
