name: Nanopi R2S Openwrt Build

on:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - r2s
  #schedule:
  #  - cron: '0 19 * * 6'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lingjiehao/build-envs:r2s
      volumes: 
        - /r2s:/r2s

    steps:
      - name: Sync
        run: |
          cd /r2s \
          && repo init -u https://github.com/lingjiehao/manifests -b r2s \
          && repo sync --no-tags -cd -j8
      
      - name: Build
        run: |
          cd /r2s \
          && ./build.sh
  
  upload:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Zip
        run: |
          mkdir ./artifact \
          && cp /r2s/bin/targets/rockchip/armv8/*squashfs-sysupgrade.img.gz ./artifact/
          && zip -r artifact.zip ./artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: Test
          path: ./artifact.zip
          
        
          
