name: Nanopi R2S Openwrt Build

on:
  workflow_dispatch:
#   push:
#     paths-ignore:
#       - '.github/**'
#     branches:
#       - r2s
  schedule:
#    - cron: '0 19 * * 6'
    - cron: '0 3 * * *'
  watch:
    types: started

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
#     container:
#       image: lingjiehao/build-envs:r2s
#       volumes: 
#         - /r2s:/r2s
    steps:
      - name: Run Docker
        run: |
          docker run -d -v /r2s:/r2s -w /r2s --name r2s-build lingjiehao/build-envs:r2s 
      - name: Sync and Build
        run: |
          docker exec r2s-build /bin/bash -c " \
            repo init -u https://github.com/lingjiehao/manifests -b r2s && \
            repo sync --no-tags -cd -j8 && \
            repo manifest -r -o static-manifest-`date +%Y-%m-%d-%H-%M`.xml ; \
            ./build.sh"

      - name: Upload ext4 Firmware
        uses: actions/upload-artifact@v2
        with:
          path: /r2s/openwrt-dev/bin/targets/rockchip/armv8/*ext4-sysupgrade.img.gz

      - name: Upload squashfs Firmware
        uses: actions/upload-artifact@v2
        with:
          path: /r2s/openwrt-dev/bin/targets/rockchip/armv8/*squashfs-sysupgrade.img.gz
       
      - name: Upload buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: buildinfo
          path: |
            /r2s/openwrt-dev/bin/targets/rockchip/armv8/*.buildinfo
            /r2s/openwrt-dev/bin/targets/rockchip/armv8/sha256sums
            /r2s/openwrt-dev/bin/targets/rockchip/armv8/*.manifest
            /r2s/static-manifest-*.xml
  
      - name: Upload packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: |
            /r2s/openwrt-dev/bin/targets/rockchip/armv8/*.buildinfo
            /r2s/openwrt-dev/bin/targets/rockchip/armv8/sha256sums
            /r2s/openwrt-dev/bin/targets/rockchip/armv8/*.manifest
            /r2s/static-manifest-*.xml      
#       - name: Upload Fail Log
#         if: ${{ failure() }}
#         uses: actions/upload-artifact@v2
#         with:
#           name: log
#           path: /r2s/build.log
        
          
