name: Nanopi R2S Openwrt Build

on:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - r2s
  #schedule:
  #  - cron: '0 19 * * 6'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lingjiehao/build-envs:r2s
      volumes: 
        - /r2s:/r2s
    steps:
      - name: Sync and Build
        run: |
          cd /r2s && \
          git config --global user.email "action@github.com" && git config --global user.name "GitHub Action" && \
          repo init -u https://github.com/lingjiehao/manifests -b r2s && \
          repo sync --no-tags -cd -j8 && \
          ./build.sh
          
