name: Nanopi R2S Openwrt Build

on:
  workflow_dispatch:
#   push:
#     paths-ignore:
#       - '.github/**'
#     branches:
#       - r2s
  #schedule:
  #  - cron: '0 19 * * 6'
#   watch:
#     types: started

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lingjiehao/build-envs:r2s
      volumes: 
        - /r2s:/r2s

    steps:
      - name: Run Docker
        run: |
          docker run -d -v /r2s:/r2s --name build-r2s lingjiehao/build-envs:r2s
      
      - name: apt
        run: |
          apt-get -y upgrate
          apt-get -y upgrade
          echo "echo 123" > /test.sh
          sh /test.sh
      
#       - name: Sync and Build
#         run: |
#             cd /r2s
#             repo init -u https://github.com/lingjiehao/manifests -b r2s
#             repo sync --no-tags -cd -j8
#             ./build.sh
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Openwrt
          path: |
            /test.sh
#            /r2s/bin/targets/rockchip/armv8/*-sysupgrade.img.gz
          
        
          
